Add "fail on failure"

diff --git a/documentation/tutorials/az-dev-ops/deploy-db/deploy-db-template.yaml b/documentation/tutorials/az-dev-ops/deploy-db/deploy-db-template.yaml
--- a/documentation/tutorials/az-dev-ops/deploy-db/deploy-db-template.yaml
+++ b/documentation/tutorials/az-dev-ops/deploy-db/deploy-db-template.yaml
@@ -13,6 +13,8 @@ jobs:
           steps:
           # Bash script:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#bash
           - bash:  |
+              # Fails if one of the command fails in the script
+              set -e
               clientVersion=$(curl https://delta-kusto.azurefd.net/clientVersion/unique?fromClientVersion=0)
               # Display the version on console
               echo "Client Version:  $clientVersion"
@@ -25,6 +27,8 @@ jobs:
             artifact: scripts
             displayName:  Download artefact 'scripts'
           - bash:  |
+              # Fails if one of the command fails in the script
+              set -e
               env=${{ parameters.env }}
               scriptFolder="$(Pipeline.Workspace)/scripts"
               echo "Environnement:  $env"
